apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-landing-app
  namespace: java-landing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-landing-app
  template:
    metadata:
      labels:
        app: java-landing-app
    spec:
      containers:
        - name: java-landing-app
          image: khadeershaik/java-landing-app:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
